### ISSUE TITLE
iOS: Device did not wake up as expected

### ISSUE THREAD

**Issue by nekohasekai** [SagerNet/sing-box#1432]
Based on feedback, some iOS devices may still be sleeping after the screen turns on (wake() not called ?). 

After a certain iOS version is updated, it is necessary to reject all connections during sleep, otherwise it will greatly increase battery consumption.

I will add an option in the new version to ignore device sleep, but this does not fundamentally solve the problem.

If any iOS developers have such experience, please help us.

**Comment by Yukariin** [comment]
It seems to be a common practice to ignore the sleep/wake function on mobile devices because it is called too often.
[1](https://github.com/eduvpn/apple/blob/master/TunnelExtension/OpenVPN/OpenVPNAdapterInterface.swift#L106) [2](https://github.com/DefinedNet/mobile_nebula/blob/master/ios/NebulaNetworkExtension/PacketTunnelProvider.swift#L113) [3](https://github.com/openziti/ziti-tunnel-apple/blob/main/Network/PacketTunnelProvider.swift#L260)

**Comment by nekohasekai** [comment]
After inspection, I found that almost all sleep events in iOS end quickly. We have taken action to ignore such events.

**Comment by HiHenryLeo** [comment]
does the latest version of SFI handled this issue?or some solutions can be use?
