### ISSUE TITLE
Question: Geo files

### ISSUE THREAD

**Issue by privatesupport** [SagerNet/sing-box#190]
In cores like xray and v2ray we have dat file. We can config routng based on that file for example direct some websites or block ads. Is there any way to use dat file or converting dat file to db file supported by sing-box?
I am asking this beacuse I already have a dat file and wish to reuse it.

**Comment by H1JK** [comment]
sing-box does not support v2fly dat file because of performance problem.  
You can check out `sing-geoip` and `sing-geosite` in SagerNet organization account.  `sing-geoip` is generated from https://github.com/Dreamacro/maxmind-geoip  
`sing-geosite` is generated from `v2fly/domain-list-community`, so it includes same data with v2fly dat geosite and has same update frequency.
