### ISSUE TITLE
[Feature Request] add wireguard amnezia to outbounds

### ISSUE THREAD

**Issue by atc891** [SagerNet/sing-box#2276]
[AmneziaWG](https://github.com/amnezia-vpn/amnezia-wg) is a contemporary version of the popular VPN protocol, WireGuard. It's a fork of [WireGuard-Go](https://github.com/WireGuard/wireguard-go) and offers protection against detection by Deep Packet Inspection (DPI) systems. At the same time, it retains the simplified architecture and high performance of the original.

The progenitor of AmneziaWG, WireGuard, is known for its efficiency, but it does have issues with detection due to distinctive packet signatures.
AmneziaWG addresses this problem by employing advanced obfuscation methods, allowing its traffic to blend seamlessly with regular internet traffic.
As a result, AmneziaWG maintains high performance while adding an extra layer of stealth, making it a superb choice for those seeking a fast and discreet VPN connection.

**Comment by X-49** [comment]
+1 Mihomo already supports AmneziaWG options, and Hiddify implements even more advanced WireGuard obfuscation. This is very valuable because we can use Warp-in-Warp to change our IP address, or in the same Hiddify example, use ProtonVPN as a basic configuration and then use the “detour” option to install the same Warp, thus changing our IP address using Cloudflare's high-speed network.

**Comment by megapro17** [comment]
Implementation is here https://github.com/amnezia-vpn/amnezia-box
