### ISSUE TITLE
【提问】在1.11.0版本中，"sniff_override_destination"配置参数将被什么替代？

### ISSUE THREAD

**Issue by sirburpalot** [SagerNet/sing-box#2407]
因使用机器翻译，如有任何错误，敬请谅解。

根据sing-box网站上的迁移说明，"sniff_override_destination"参数将在1.11.0版本中被弃用。但遗憾的是，文档中并未说明该参数的替代方案。请问有人知道将会使用什么参数来替代吗？先行谢过。

**Comment by luweijun1992** [comment]
如下，好像现在找不到文档说明了，不知道啥情况
```
    "route": {
        "rules": [
            {
                "action": "sniff"
            },
```

**Comment by nekohasekai** [comment]
Use fake-ip instead.

**Comment by Mahdi-zarei** [comment]
> Use fake-ip instead.

There are use cases where fakeIP will not handle the lack of override destination. One case is that discord does not use system proxy on windows, and in Iran, only the domains and the IPs behind them are blocked and the webRTC servers are accessible, so one think I did was that I edited the host file to resolve discord domains to localhost, then ran sing-box with a direct inbound with sniff_override_destination, this essentially made it possible to route only discord without using Tun mode which can affect the ping in some games due to my server's location and also avoid complicated routing rules to bypass some apps etc. So if possible, I would like to ask you to consider keeping sniff_override_destination in the route settings.

**Comment by nekohasekai** [comment]
> > Use fake-ip instead.
> 
> There are use cases where fakeIP will not handle the lack of override destination. One case is that discord does not use system proxy on windows, and in Iran, only the domains and the IPs behind them are blocked and the webRTC servers are accessible, so one thing I did was that I edited the host file to resolve discord domains to localhost, then ran sing-box with a direct inbound with sniff_override_destination, this essentially made it possible to route only discord without using Tun mode which can affect the ping in some games due to my server's location and also avoid complicated routing rules to bypass some apps etc. So if possible, I would like to ask you to consider keeping sniff_override_destination in the route settings.

This is typical smart-assed stuff, please first learn how DNS and TCP/IP work.

**Comment by Mahdi-zarei** [comment]
> > > Use fake-ip instead.
> > 
> > 
> > There are use cases where fakeIP will not handle the lack of override destination. One case is that discord does not use system proxy on windows, and in Iran, only the domains and the IPs behind them are blocked and the webRTC servers are accessible, so one thing I did was that I edited the host file to resolve discord domains to localhost, then ran sing-box with a direct inbound with sniff_override_destination, this essentially made it possible to route only discord without using Tun mode which can affect the ping in some games due to my server's location and also avoid complicated routing rules to bypass some apps etc. So if possible, I would like to ask you to consider keeping sniff_override_destination in the route settings.
> 
> This is typical smart-assed stuff, please first learn how DNS and TCP/IP work.

I'm sorry if I'm misunderstanding, but to clarify the situation, Iran is running a strict SNI filtering both domestically(on some ISPs) and on Foreign routers. So no connection with the SNI of discord.gg etc can be established. The only solution I know is that to somehow tunnel the connection, which can either be done by the application, which it does not do in discord's case, or to use a transparent proxy. So I either have to choose between a Tun interface along with some external routing rules or internal(sing-box) rules to tunnel the traffic i want, or I have to somehow redirect the connection into sing-box and route it back from there. If there is any other way, I am very curious and appreciate it if you could tell me about it. The only way I can think of besides what I have mentioned, is to somehow set sing-box as my dns server with fake-ip enabled, then use the Tun mode to only route the fake-ip subnet so that I can practically achieve the same effect, although with Run interface engaged.

**Comment by BK8000L** [comment]
this feature allowed to make a smart-dns proxy server, sad so see it go away

**Comment by jazz4110** [comment]
I need this feature because I want to use doh and ech in firefox but it usually returns bad ip.

**Comment by dqgyfl** [comment]
pls consider add sniff_override_destination back, 
fake ip is not stable, 
I'm always facing the issue of application use old/stale fake ip address
even when I enable experimental cache file to store facke ip

**Comment by dqgyfl** [comment]
@nekohasekai 

pls consider add  `sniff_override_destination`  back,
fake ip is not stable,
I'm always facing the issue of application use old/stale fake ip address
even when I enable experimental cache file to store facke ip

**Comment by wwbfred** [comment]
我能理解作者的想法，大部分场景比起使用sniff_override_destination都有更好的替代方案。
但由于探测并覆盖的想法源自V2RAY，这产生了大量与其相关的架构设计，也的确有很多人通过各种合理或是不太合理的方式使用到了这个功能。
个人认为如果不是影响代码重构和功能设计的重大因素，可以考虑保留。谢谢。
