### ISSUE TITLE
Feature Request: Add support for Simple WireGuard proxy

### ISSUE THREAD

**Issue by degfw** [SagerNet/sing-box#457]
Hello,

I want to express my appreciation for the hard work of the developers who added WireGuard support to sing-box. However, As we known, WireGuard doesn't work well in countries with strict censorship policies, such as China and Iran. Fortunately, I've found a solution that could help: [swgp-go](https://github.com/database64128/swgp-go).

If sing-box could incorporate support for [swgp-go](https://github.com/database64128/swgp-go), users would have access to even more options and enjoy a better overall experience.

**Comment by database64128** [comment]
Hi, author of swgp-go here.

Is there any particular reason for choosing WireGuard instead of general-purpose proxy protocols like Shadowsocks for your use case? As you may already know, I also maintain https://github.com/database64128/shadowsocks-go, which was kept separate from swgp-go, because their use cases do not overlap.

swgp-go also does not guarantee a stable protocol, unlike the protocols implemented by sing-box and shadowsocks-go. There have been breaking changes to the protocol in the past, and I do not yet have any plans to stabilize it.

**Comment by database64128** [comment]
> However, I understand from your response that there are no current plans to improve swgp-go in the future.

I think you misunderstood what I meant. I was merely stating that there are no plans for swgp-go to settle on a stable protocol. This strategy allows swgp-go to **keep its simplicity and iterate quickly**. I may implement a breaking protocol change at any time and it might break backward compatibility with previous versions.

This is why I didn't integrate swgp-go into shadowsocks-go, and why I don't think it's fit for sing-box to implement it. They have very different use cases and provide different stability guarantees, and it's very easy to use sing-box's WireGuard outbound together with swgp-go.
