### ISSUE TITLE
[Feature Request]: Implementing TLS Client Hello Fragmentation

### ISSUE THREAD

**Issue by molink36** [SagerNet/sing-box#823]
When GTW wants to block a website, it poisons DNS replies, and blocks connections based on the the domain name sniffed from the TLS protocol. This can be overcome by fragmenting TLS Client Hello, in combination with "DNS over HTTPS". It would be great if different methods to fragment TLS connection and bypass deep packet inspection were implemented in sing-box.

An excellent example of such program is GoodbyeDPI, which is working great:
[https://github.com/ValdikSS/GoodbyeDPI](url)

More discussion:
[https://github.com/XTLS/Xray-core/issues/1996](url)
[https://github.com/XTLS/Xray-core/issues/2000](url)

**Comment by nekohasekai** [comment]
According to discussions from Xray issues, this method doesn't work (or rarely does) right now, so I don't care about this. But if you can provide excellent code, I will still consider it.

**Comment by DeadSecure** [comment]
hello
this is an amazing code about fragment clienthello 
can you please add this in sing-box?
https://github.com/projectdiscovery/tlsx/compare/main...rrouzbeh:tlsx:main?diff=split

**Comment by kyochikuto** [comment]
@nekohasekai So where do you propose to implement this? Introducing it as a buffer writer in [sing](https://github.com/SagerNet/sing) or modifying outbound Direct implementation in [sing-box](https://github.com/SagerNet/sing-box)? Although the latter sounds a bit more hacky!
[tfo-go](https://github.com/SagerNet/tfo-go) is another option since we're only targeting TCP connections to fragment but I believe that would introduce unnecessary complications for apps relying on tfo-go.
