### ISSUE TITLE
Do not deprecate proxy protocol

### ISSUE THREAD

**Issue by hiddify-com** [SagerNet/sing-box#867]
Based on https://sing-box.sagernet.org/deprecated/ it seems that you want to deprecated proxy protocol.
However, please do not do such since an important future feature is for limiting the number of IP connecting to the server. 
And putting singbox behind HAProxy is needed for hiding using proxy otherwise it will be easily detected by GFW.

Please do not remove proxy protocol

**Comment by nekohasekai** [comment]
This has little effect on individual users and the black industry, because there is no evidence that GFW will actively initiate HTTPS requests and perform blocks based on the responses. If you believe server TLS fingerprinting played a role in the blockade, please report it to the academic community.

You work for a **closed source project that looks open source**, so I assume no one will agree with your request.

In addition, China's proxy black industry hardly relies on proxy protocols to pass through GFW, and does not need HTTP multiplexers, but only uses their graphical clients to provide services.

**Comment by hiddify-com** [comment]
I'd like to clarify that we are indeed a **fully open-source project**.  For only a short period where we had to make the UI closed-source due to some individuals not adhering to the open-source license terms and no one knows us and they attempted to sell the panel to others. However, after we are known enough we have reverted it back to being fully open-source.

You can find the full source code of our server setup:
- [WebUI for User and System Management](https://github.com/hiddify/HiddifyPanel)
- [Server Setup](https://github.com/hiddify/hiddify-config/) and [haproxy configuration for singbox](https://github.com/hiddify/hiddify-config/blob/main/haproxy/singbox.cfg.template)
- [Singbox configs](https://github.com/hiddify/hiddify-config/tree/main/singbox/configs)

We are happy to offer a configurable SingBox server complete with user management, entirely for free and open to the public under an open-source license.

I understand that some bad behavior can happen with proxy protocol but i it can be happen with other protocols like vless over http.

I kindly request to not deprecate proxy-protocol. You can also make it available only for localhost
